default : UI/hw2_ui.py
	python3 hw2.py

q5: UI/hw2_5_ui.py
	python3 hw2_5.py

hw2_ui.py : UI/hw2_ui.ui
	pyuic5 -x UI/hw2_ui.ui -o UI/hw2_ui.py

hw2_5_ui.py: UI/hw2_5_ui.ui
	pyuic5 -x UI/hw2_5_ui.ui -o UI/hw2_5_ui.py